package ar.edu.unq.epersgeist.modelo.ritual;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;


@Getter
@Setter
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ritual")
public class Ritual {
    @DynamoDBHashKey(attributeName = "ritualId")
    @DynamoDBAutoGeneratedKey
    private String ritualId;


    @DynamoDBAttribute
    private String nombre;

    @DynamoDBAttribute
    private String medium;

    @DynamoDBAttribute
    private String palabrasRitual = "";

    @DynamoDBAttribute
    private int energiaRitual = 0;

    public Ritual(String nombre, String medium, String palabrasRitual) {
        this.nombre = nombre;
        this.medium = medium;
        this.palabrasRitual = palabrasRitual;
    }

    public Ritual(String nombre, String medium, String palabrasRitual, String ritualId) {
        this.nombre = nombre;
        this.medium = medium;
        this.palabrasRitual = palabrasRitual;
        this.ritualId = ritualId;
    }

    @DynamoDBIgnore
    public List<String> getPalabrasDelRitual() {
        return Stream.of(palabrasRitual.trim().split("\\s+"))
                .map(String::toLowerCase)
                .toList();
    }

}